version: '3.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/volume:/var/lib/mongodb
      - ./mongodb/config/mongodb.conf:/etc/mongod.conf
      - ./mongodb/log/:/var/log/mongodb/
    command: ['-f', '/etc/mongod.conf']
