version: '3.1'
services:
  mongodb2:
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/config/mongod.conf:/etc/mongod.conf
      - ./mongodb/data/log/:/var/log/mongodb
      - ./mongodb/data/volume:/var/lib/mongodb
    command: ['-f', '/etc/mongod.conf']
